### ISSUE TITLE
AttributeError: 'ModelParams' object has no attribute 'stellar_model'

### ISSUE THREAD

**Issue by tcjansen** [tomlouden/SPIDERMAN#24]
Hi there, 

I ran into a problem when going through the Quickstart example in the documentation. When it came to this line,

`lc = spider_params.lightcurve(t)`

I receive this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python3.5/site-packages/spiderman_package-1.0.0-py3.5-macosx-10.6-x86_64.egg/spiderman/params.py", line 356, in lightcurve
    return sp.lightcurve(t,self,**kwargs)
  File "//anaconda/lib/python3.5/site-packages/spiderman_package-1.0.0-py3.5-macosx-10.6-x86_64.egg/spiderman/web.py", line 95, in lightcurve
    star_grid = sp.stellar_grid.gen_grid(spider_params.l1,spider_params.l2,logg=logg,response=spider_params.filter, stellar_model = spider_params.stellar_model)
AttributeError: 'ModelParams' object has no attribute 'stellar_model'
```
When importing spiderman I also received this note, which might be of relevence?:
```
looking for spidermanrc file at ~/.spidermanrc
no spidermanrc file detected
```

Help would be appreciated, thanks!

**Comment by lkreidberg** [comment]
hmm the quickstart example works with my (slightly out-of-date) version of spiderman. Are you using the latest version? if so, it's probably a bug introduced recently

**Comment by tcjansen** [comment]
Yes, I tried both the pip installable version and the github version (cloned yesterday) and got the same error both times 🤔

**Comment by tomlouden** [comment]
Hi Tiffany,

Sorry about that, I was not sufficiently careful when uploading a recent patch, if you re-install from either source it should work now, please let me know if it doesn't!

Tom

On 10/09/2019 19:20, Tiffany Jansen wrote:

Yes, I tried both the pip installable version and the github version (cloned yesterday) and got the same error both times 🤔

**Comment by tcjansen** [comment]
Quickstart works for me now, thanks!
